export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$HOME/.composer/vendor/bin:/opt/homebrew/opt/python@3.11/libexec/bin:/opt/homebrew/opt/php@8.2/bin:/opt/homebrew/opt/php@8.2/sbin:$HOME/Dev/chess.com/kotr/bin:$PATH

eval "$(/opt/homebrew/bin/brew shellenv)"

# Oh-My-Zsh config
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="gwent"
CASE_SENSITIVE="true"
plugins=(git docker docker-compose)

source $ZSH/oh-my-zsh.sh

unsetopt inc_append_history
unsetopt share_history

# User configuration
export LANG=en_US.UTF-8export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

export LESSCHARSET=utf-8

export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/kipelovets/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/kipelovets/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/kipelovets/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/kipelovets/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

CUSTOM_CONFIG="$HOME/.zshrc.dist"
if [ -f $CUSTOM_CONFIG ]; then . "$CUSTOM_CONFIG"; else echo "Custom config not found"; fi
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

function __notif() {
    osascript -e "display notification \"$1\" with title \"Chess 👸\" sound name \"Glass\""
}

function rowdy() {
    echo "Executing '$@'"
    $@ && __notif "OK: $comment ✅" || __notif "FAILED: $comment ⛔"
}
