export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$HOME/.composer/vendor/bin:$PATH

eval "$(/opt/homebrew/bin/brew shellenv)"

# Oh-My-Zsh config
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="gwent"
CASE_SENSITIVE="true"
plugins=(git docker docker-compose)

source $ZSH/oh-my-zsh.sh

unsetopt inc_append_history
unsetopt share_history

# User configuration
export LANG=en_US.UTF-8export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/georgii.korshunov/Dev/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/georgii.korshunov/Dev/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/georgii.korshunov/Dev/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/georgii.korshunov/Dev/google-cloud-sdk/completion.zsh.inc'; fi

export LESSCHARSET=utf-8
